"""Method catalog and applicability matrix.

Each entry records the mathematical minimum anchor/satellite count
separately from the preferred benchmark count, and whether this project
has a native simulator for the method or relies on sourced/imported
evidence (measured, published, or official) instead. Per the requirements,
not every method gets a bespoke simulator: methods without one are
compared using imported evidence, and that fact is recorded here rather
than papered over with an invented model.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class MethodDefinition:
    name: str
    family: str  # "LOCAL_RADIO" | "GNSS" | "OTHER"
    display_name: str
    mathematical_minimum_anchors: Optional[int]
    preferred_benchmark_anchors: Optional[int]
    has_native_simulator: bool
    evidence_note: str = ""
    is_local_radio_anchor_based: bool = False
    is_gnss: bool = False
    is_rtk: bool = False
    is_ppp: bool = False
    uses_active_radio_airtime: bool = False
    uses_correction_link: bool = False


def _local(
    name,
    display_name,
    math_min,
    preferred,
    has_sim,
    note="",
    airtime=True,
) -> MethodDefinition:
    return MethodDefinition(
        name=name,
        family="LOCAL_RADIO",
        display_name=display_name,
        mathematical_minimum_anchors=math_min,
        preferred_benchmark_anchors=preferred,
        has_native_simulator=has_sim,
        evidence_note=note,
        is_local_radio_anchor_based=math_min is not None,
        uses_active_radio_airtime=airtime,
    )


METHOD_CATALOG: dict[str, MethodDefinition] = {
    "SX1280_RANGING": _local(
        "SX1280_RANGING", "Semtech SX1280 ranging (pairwise)", 2, 2, True,
        "Native pairwise-ranging simulator plus hardware-calibrated model "
        "from Stuart Robinson's published data (see hardware.sx1280_error_model).",
    ),
    "UWB_SS_TWR": _local("UWB_SS_TWR", "UWB SS-TWR trilateration", 4, 5, True),
    "UWB_DS_TWR": _local("UWB_DS_TWR", "UWB DS-TWR trilateration", 4, 5, True),
    "TDOA": _local("TDOA", "TDoA (synchronized anchors)", 4, 5, True),
    "TOA": _local("TOA", "ToA with common time base", 4, 5, True),
    "TOF": _local("TOF", "Time of flight (one-way)", 4, 5, True),
    "GENERIC_RTT": _local("GENERIC_RTT", "Generic round-trip-time ranging", 4, 5, True),
    "WIFI_RTT_FTM": _local(
        "WIFI_RTT_FTM", "Wi-Fi RTT / IEEE 802.11mc FTM", 4, 5, True,
        "Native TWR-style simulator; per-vendor FTM accuracy claims kept as "
        "OFFICIAL_SPECIFICATION/PUBLISHED_EXPERIMENT evidence, not simulated.",
    ),
    "BLE_AOA": _local(
        "BLE_AOA", "BLE angle of arrival", None, None, False,
        "Angle-based observability depends on antenna array geometry, not a "
        "trilateration anchor count; no bespoke AoA simulator is included. "
        "Compared using imported/sourced evidence.",
        airtime=True,
    ),
    "BLE_AOD": _local(
        "BLE_AOD", "BLE angle of departure", None, None, False,
        "Same rationale as BLE_AOA: array-geometry dependent, sourced evidence only.",
    ),
    "RSSI_TRILATERATION": _local("RSSI_TRILATERATION", "RSSI trilateration", 4, 5, True),
    "FINGERPRINTING": _local(
        "FINGERPRINTING", "RF fingerprinting", None, None, False,
        "No trilateration minimum applies; accuracy depends on reference-map "
        "density, not anchor geometry. Compared using imported/sourced evidence.",
        airtime=False,
    ),
    "RFID": _local(
        "RFID", "RFID proximity/ranging", None, None, False,
        "Highly implementation-specific (proximity vs phase-ranging RFID); "
        "compared using imported/sourced evidence rather than one simulator.",
    ),
    "ACOUSTIC_RANGING": _local(
        "ACOUSTIC_RANGING", "Acoustic (ultrasonic) ranging", 4, 5, True,
        "Uses the same TWR/ToA solver as the RF-based methods, operating "
        "directly on range-domain measurements; the solver has no "
        "dependence on propagation speed either way, so no acoustic-"
        "specific propagation physics (attenuation, reflection, medium "
        "temperature/humidity dependence) is simulated.",
    ),
}


def _gnss(name, display_name, is_rtk=False, is_ppp=False) -> MethodDefinition:
    return MethodDefinition(
        name=name,
        family="GNSS",
        display_name=display_name,
        mathematical_minimum_anchors=None,
        preferred_benchmark_anchors=None,
        has_native_simulator=False,
        evidence_note=(
            "GNSS results are imported from receiver logs or official/"
            "published sources (see gnss.model), not generated by a project "
            "GNSS signal simulator."
        ),
        is_gnss=True,
        is_rtk=is_rtk,
        is_ppp=is_ppp,
        uses_correction_link=is_rtk or is_ppp,
    )


METHOD_CATALOG.update(
    {
        "GNSS_SPP": _gnss("GNSS_SPP", "GNSS standalone SPP"),
        "GNSS_SBAS": _gnss("GNSS_SBAS", "GNSS with SBAS correction"),
        "GNSS_DGNSS": _gnss("GNSS_DGNSS", "GNSS with DGNSS correction"),
        "GNSS_RTK_FLOAT": _gnss("GNSS_RTK_FLOAT", "GNSS RTK float", is_rtk=True),
        "GNSS_RTK_FIXED": _gnss("GNSS_RTK_FIXED", "GNSS RTK fixed", is_rtk=True),
        "GNSS_NETWORK_RTK": _gnss("GNSS_NETWORK_RTK", "GNSS network RTK", is_rtk=True),
        "GNSS_PPK": _gnss("GNSS_PPK", "GNSS post-processed kinematic", is_rtk=True),
        "GNSS_PPP": _gnss("GNSS_PPP", "GNSS PPP", is_ppp=True),
        "GNSS_PPP_AR": _gnss("GNSS_PPP_AR", "GNSS PPP-AR", is_ppp=True),
        "GNSS_HAS": _gnss("GNSS_HAS", "GNSS with HAS correction", is_ppp=True),
        "GNSS_PLUS_INS": _gnss("GNSS_PLUS_INS", "GNSS plus INS"),
    }
)


def _other(name, display_name, note) -> MethodDefinition:
    return MethodDefinition(
        name=name,
        family="OTHER",
        display_name=display_name,
        mathematical_minimum_anchors=None,
        preferred_benchmark_anchors=None,
        has_native_simulator=False,
        evidence_note=note,
    )


METHOD_CATALOG.update(
    {
        "VISUAL_LOCALIZATION": _other(
            "VISUAL_LOCALIZATION", "Visual localization",
            "No bespoke visual-localization simulator; compared using "
            "imported/sourced evidence (published benchmarks, vendor specs).",
        ),
        "VIO": _other(
            "VIO", "Visual-inertial odometry",
            "Drift-dominated, trajectory- and scene-dependent; sourced evidence only.",
        ),
        "SLAM": _other(
            "SLAM", "Simultaneous localization and mapping",
            "Highly implementation- and sensor-dependent; sourced evidence only.",
        ),
        "LIDAR_LOCALIZATION": _other(
            "LIDAR_LOCALIZATION", "LiDAR localization",
            "Map/scan-matching dependent; sourced evidence only.",
        ),
        "INS": _other(
            "INS", "Inertial navigation",
            "Pure inertial drift is sensor-grade dependent; sourced evidence only.",
        ),
        "PDR": _other(
            "PDR", "Pedestrian dead reckoning",
            "Gait- and sensor-dependent; sourced evidence only.",
        ),
        "MAGNETIC_FINGERPRINTING": _other(
            "MAGNETIC_FINGERPRINTING", "Magnetic fingerprinting",
            "Site-survey dependent, no trilateration minimum; sourced evidence only.",
        ),
        "HYBRID_LOCALIZATION": _other(
            "HYBRID_LOCALIZATION", "Hybrid (sensor-fused) localization",
            "Fusion-architecture dependent; sourced evidence only.",
        ),
    }
)


def get_method(name: str) -> MethodDefinition:
    if name not in METHOD_CATALOG:
        raise KeyError(f"Unknown method {name!r}. Known: {sorted(METHOD_CATALOG)}")
    return METHOD_CATALOG[name]


_APPLICABILITY_METRICS = (
    "anchor_count",
    "satellite_count",
    "rtk_convergence",
    "ppp_convergence",
    "radio_airtime",
    "correction_link_traffic",
)


def applicability_matrix() -> dict[str, dict[str, bool]]:
    """Which scalability/GNSS-specific metrics apply to which method."""
    matrix: dict[str, dict[str, bool]] = {}
    for name, m in METHOD_CATALOG.items():
        matrix[name] = {
            "anchor_count": m.is_local_radio_anchor_based,
            "satellite_count": m.is_gnss,
            "rtk_convergence": m.is_rtk,
            "ppp_convergence": m.is_ppp,
            "radio_airtime": m.uses_active_radio_airtime,
            "correction_link_traffic": m.uses_correction_link,
        }
    return matrix
